### ISSUE TITLE
Kurzbeschreibung der Sortieridee

### ISSUE THREAD

**Issue by ApertureDevelopment** [ApertureDevelopment/gi-lam-project#10]
Hierbei ist eine kleine beschreibung zu erstellen wie genau die SOrtieridee mit dem Array arbeitet und Sortiert

**Comment by Alltagshuebsch** [comment]
[GI Sortieralgorithmus.pdf](https://github.com/user-attachments/files/15929289/GI.Sortieralgorithmus.pdf)
Hier findet sich die Erklärung des Sortieralgorithmus inklusive Struktogramm.
